import { PaginationProps } from 'antd'

// 批次分布
export const batchLine = (pagination: PaginationProps) => [
  {
    title: '序号',
    // render: (text: any, record: any, index: number) => (pagination.current - 1) * pagination.pageSize + index + 1,
    align: 'center',
    width: 50,
  },
  {
    title: '班级',
    dataIndex: 'className',
    key: 'className',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '班主任',
    dataIndex: 'teacherName',
    key: 'teacherName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '所属学校',
    dataIndex: 'schoolName',
    key: 'schoolName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '一批次人数',
    dataIndex: 'firstBatchNum',
    key: 'firstBatchNum',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '一批次比例',
    dataIndex: 'firstBatchPro',
    key: 'firstBatchPro',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '二批次人数',
    dataIndex: 'secondBatchNum',
    key: 'secondBatchNum',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '二批次比例',
    dataIndex: 'secondBatchPro',
    key: 'secondBatchPro',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '三批次人数',
    dataIndex: 'thirdBatchNum',
    key: 'thirdBatchNum',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '三批次比例',
    dataIndex: 'thirdBatchPro',
    key: 'thirdBatchPro',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '四批次人数',
    dataIndex: 'fourthBatchNum',
    key: 'fourthBatchNum',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '四批次比例',
    dataIndex: 'fourthBatchPro',
    key: 'fourthBatchPro',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
]
// 班级排名
export const classRanking = (pagination: PaginationProps) => [
  {
    title: '序号',
    // render: (text: any, record: any, index: number) => (pagination.current - 1) * pagination!.pageSize + index + 1,
    align: 'center',
  },
  {
    title: '班级',
    dataIndex: 'objectName',
    key: 'objectName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '班主任',
    dataIndex: 'teacherName',
    key: 'teacherName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '所属学校',
    dataIndex: 'schoolName',
    key: 'schoolName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '联考前10名',
    dataIndex: 'tenNum',
    key: 'tenNum',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '联考前50名',
    dataIndex: 'fifthNum',
    key: 'fifthNum',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '联考前100名',
    dataIndex: 'oneHundredNum',
    key: 'oneHundredNum',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '联考前200名',
    dataIndex: 'twoHundredNum',
    key: 'twoHundredNum',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
]
// 成绩分布
export const scoreLine = (pagination: PaginationProps) => [
  {
    title: '序号',
    // render: (text: any, record: any, index: number) => (pagination.current - 1) * pagination.pageSize + index + 1,
    align: 'center',
  },
  {
    title: '班级',
    dataIndex: 'className',
    key: 'className',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '班主任',
    dataIndex: 'teacherName',
    key: 'teacherName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '所属学校',
    dataIndex: 'schoolName',
    key: 'schoolName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '优秀人数',
    dataIndex: 'excellentNum',
    key: 'excellentNum',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '优秀比例',
    dataIndex: 'excellentRate',
    key: 'excellentRate',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '良好人数',
    dataIndex: 'goodNum',
    key: 'goodNum',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '良好比例',
    dataIndex: 'goodRate',
    key: 'goodRate',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '及格人数',
    dataIndex: 'passNum',
    key: 'passNum',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '及格比例',
    dataIndex: 'passRate',
    key: 'passRate',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '不及格人数',
    dataIndex: 'noPassNum',
    key: 'noPassNum',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '不及格比例',
    dataIndex: 'noPassRate',
    key: 'noPassRate',
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
]

// 班级报告单科
export const classSingle = (pagination: PaginationProps) => [
  {
    title: '名次',
    // render: (text: any, record: any, index: number) => (pagination.current - 1) * pagination.pageSize + index + 1,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '班级',
    dataIndex: 'className',
    key: 'className',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '任课老师',
    dataIndex: 'teacherName',
    key: 'teacherName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '所属学校',
    dataIndex: 'schoolName',
    key: 'schoolName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '平均分',
    render: (text: any, record: { subjectList: { avgScore: any }[] }) => record.subjectList[0].avgScore,
    sorter: true,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '与联考平均分差',
    render: (text: any, record: { subjectList: { diff: any }[] }) => record.subjectList[0].diff,
    align: 'center',
    ellipsis: true,
  },
]
