// 批次分布
export const batchLine = [
  {
    title: '序号',
    render: (text, record, index) => index + 1,
    align: 'center',
    width: 50,
  },
  {
    title: '班级',
    dataIndex: 'className',
    key: 'className',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '班主任',
    dataIndex: 'teacherName',
    key: 'teacherName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '所属学校',
    dataIndex: 'schoolName',
    key: 'schoolName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '一批次人数',
    dataIndex: 'firstBatchNum',
    key: 'firstBatchNum',
    sorter: (a, b) => a.firstBatchNum - b.firstBatchNum,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '一批次比例',
    dataIndex: 'firstBatchPro',
    key: 'firstBatchPro',
    sorter: (a, b) => a.firstBatchPro - b.firstBatchPro,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '二批次人数',
    dataIndex: 'secondBatchNum',
    key: 'secondBatchNum',
    sorter: (a, b) => a.secondBatchNum - b.secondBatchNum,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '二批次比例',
    dataIndex: 'secondBatchPro',
    key: 'secondBatchPro',
    sorter: (a, b) => a.secondBatchPro - b.secondBatchPro,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '三批次人数',
    dataIndex: 'thirdBatchNum',
    key: 'thirdBatchNum',
    sorter: (a, b) => a.thirdBatchNum - b.thirdBatchNum,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '三批次比例',
    dataIndex: 'thirdBatchPro',
    key: 'thirdBatchPro',
    sorter: (a, b) => a.thirdBatchPro - b.thirdBatchPro,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '四批次人数',
    dataIndex: 'fourthBatchNum',
    key: 'fourthBatchNum',
    sorter: (a, b) => a.fourthBatchNum - b.fourthBatchNum,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '四批次比例',
    dataIndex: 'fourthBatchPro',
    key: 'fourthBatchPro',
    sorter: (a, b) => a.fourthBatchPro - b.fourthBatchPro,
    align: 'center',
    ellipsis: true,
  },
];
// 班级排名
export const classRanking = [
  {
    title: '序号',
    render: (text, record, index) => index + 1,
    align: 'center',
  },
  {
    title: '班级',
    dataIndex: 'objectName',
    key: 'objectName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '班主任',
    dataIndex: 'teacherName',
    key: 'teacherName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '所属学校',
    dataIndex: 'schoolName',
    key: 'schoolName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '联考前10名',
    dataIndex: 'tenNum',
    key: 'tenNum',
    sorter: (a, b) => a.tenNum - b.tenNum,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '联考前50名',
    dataIndex: 'fifthNum',
    key: 'fifthNum',
    sorter: (a, b) => a.fifthNum - b.fifthNum,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '联考前100名',
    dataIndex: 'oneHundredNum',
    key: 'oneHundredNum',
    sorter: (a, b) => a.oneHundredNum - b.oneHundredNum,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '联考前200名',
    dataIndex: 'twoHundredNum',
    key: 'twoHundredNum',
    sorter: (a, b) => a.twoHundredNum - b.twoHundredNum,
    align: 'center',
    ellipsis: true,
  },
];
// 成绩分布
export const scoreLine = [
  {
    title: '序号',
    render: (text, record, index) => index + 1,
    align: 'center',
  },
  {
    title: '班级',
    dataIndex: 'className',
    key: 'className',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '班主任',
    dataIndex: 'teacherName',
    key: 'teacherName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '所属学校',
    dataIndex: 'schoolName',
    key: 'schoolName',
    align: 'center',
    ellipsis: true,
  },
  {
    title: '优秀人数',
    dataIndex: 'excellentNum',
    key: 'excellentNum',
    sorter: (a, b) => a.excellentNum - b.excellentNum,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '优秀比例',
    dataIndex: 'excellentRate',
    key: 'excellentRate',
    sorter: (a, b) => a.excellentRate - b.excellentRate,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '良好人数',
    dataIndex: 'goodNum',
    key: 'goodNum',
    sorter: (a, b) => a.goodNum - b.goodNum,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '良好比例',
    dataIndex: 'goodRate',
    key: 'goodRate',
    sorter: (a, b) => a.goodRate - b.goodRate,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '及格人数',
    dataIndex: 'passNum',
    key: 'passNum',
    sorter: (a, b) => a.passNum - b.passNum,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '及格比例',
    dataIndex: 'passRate',
    key: 'passRate',
    sorter: (a, b) => a.passRate - b.passRate,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '不及格人数',
    dataIndex: 'noPassNum',
    key: 'noPassNum',
    sorter: (a, b) => a.noPassNum - b.noPassNum,
    align: 'center',
    ellipsis: true,
  },
  {
    title: '不及格比例',
    dataIndex: 'noPassRate',
    key: 'noPassRate',
    sorter: (a, b) => a.noPassRate - b.noPassRate,
    align: 'center',
    ellipsis: true,
  },
];
